### ISSUE TITLE
writing integer values

### ISSUE THREAD

**Issue by tchaloupka** [kaleidicassociates/influx-d#14]
After last change when string fields are automatically quoted, one lost the ability to tweak formatting of integer values.

They are written like `value=42i`, otherwise influxdb handles all numbers as a float.

Now it will write this value as a quoted string.

I'm not sure how to handle this, but what comes to mind:
* try to parse string parameter as int if it ends with `i`
* use Variant type as a fields AA value type instead of string so it can contain bool, int, double and string values and format them based on the type

**Comment by atilaneves** [comment]
Both of your solutions are valid. I'll fix this either way. I had no idea about the `i` suffix and only found out about quoting strings when my inserts failed without them. Thanks for reporting the issue.
