### ISSUE TITLE
new release pls

### ISSUE THREAD

**Issue by tchaloupka** [kaleidicassociates/influx-d#23]
Can I ask for the new release please? :)

**Comment by atilaneves** [comment]
Done.

**Comment by tchaloupka** [comment]
thanks, but I don't see any? still 0.2.12 is the latest

**Comment by atilaneves** [comment]
I think I was half asleep when I tried doing this, I tagged and pushed a different repository. I just fixed it now. Sorry about that.

**Comment by tchaloupka** [comment]
no problem, thanks :)
