### ISSUE TITLE
vibe-core enforced

### ISSUE THREAD

**Issue by tchaloupka** [kaleidicassociates/influx-d#6]
I'm not sure if it is not too early to do so. Might be better to move it to influx-d configurations and let the users choose the variant?
For example we are still using old core because the new one is pretty slow (http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/42833/) and has other changes too, but with v0.2.3 the new one is forced and I don't know the way to overcome it with dub (other than use v0.2.2)

**Comment by atilaneves** [comment]
That's a good point, especially since what this was trying to accomplish didn't quite work on Windows. There was a reason for it though.
