### ISSUE TITLE
Not compilable on linux with openssl version >1.0.0 and <1.1

### ISSUE THREAD

**Issue by tchaloupka** [kaleidicassociates/influx-d#7]
After last modification of posix lib dependencies, it won't compile on Fedora26.

These are the problem:
```
":libssl.so.1.0.0",
":libcrypto.so.1.0.0"
```

Libs on updated Fedora:
```
/usr/lib/libcrypto.so.10 -> libcrypto.so.1.0.2k
/usr/lib/libcrypto.so.1.0.2k
/usr/lib/libssl.so.10 -> libssl.so.1.0.2k
/usr/lib/libssl.so.1.0.2k
```

**Comment by atilaneves** [comment]
I don't know how to fix this properly then. The problem is vibe.d. Without this it won't compile on Arch Linux. I also don't have Fedora installed so I can't really debug this.

**Comment by tchaloupka** [comment]
Well is it even needed here as it is only used by vibe directly? As this is just a lib maybe this should be left to be sorted on the user side?

We have a couple of projects which have just set the dependency of `"openssl": "~>1.1.5+1.0.1g"` deimos package which vibe-d optionally use and it works at least with Fedora 26 and at Ubuntu server 16.04.2 LTS.
Don't know about Arch though.

Might be better to also use just vibe-d:http dependency instead of the whole vibe-d?

**Comment by atilaneves** [comment]
It's needed. Without adding that it just doesn't compile on Arch Linux. I only even know about the solution because of [this vibe issue](https://github.com/rejectedsoftware/vibe.d/issues/1748). The problem is that Arch has a newer version of SSL that breaks the deimos bindings.

I'm pretty sure `vibe-d:http` wouldn't help since the problem is SSL related.

**Comment by tchaloupka** [comment]
Then maybe as a workaround introduce sub configuration for openssl v1.0.x and v1.1?
So the lib user can choose. But I think that this should go to vibe-d or even to openssl instead as it's not the influx-d problem.
