### ISSUE TITLE
SysTime from ISOExtString not allways works

### ISSUE THREAD

**Issue by tchaloupka** [kaleidicassociates/influx-d#9]
If you let the influxdb set the time and then try to read it back, you get:

```
Invalid ISO Extended String: 2017-05-10T14:47:38.582524801Z
/usr/include/dmd/phobos/std/datetime.d:8816 @safe std.datetime.SysTime std.datetime.SysTime.fromISOExtString!(immutable(char)[]).fromISOExtString(const(immutable(char)[]), immutable(std.datetime.TimeZone)) [0xf1a524]
../../../../../.dub/packages/influx-d-0.2.5/influx-d/source/influxdb/api.d:337 const(@safe std.datetime.SysTime function()) influxdb.api.MeasurementSeries.Rows.Row.time [0x115e36d]\nsource/dal/ntf/influxdb.d:130
```

Problem is that SysTime works only with hnsecs, but it receives nsecs and so input is too long.

I've some time ago filled this bug to phobos: https://issues.dlang.org/show_bug.cgi?id=16053
So it should probably get fixed in the phobos.

**Comment by atilaneves** [comment]
I can't fix Phobos here but I can try to work around it, so I have.
